'use client';
import { useMemo, useState } from 'react';
import SitePreview from '../../lib/SitePreview';
import { createDefaultSite, templateLibrary, getTemplate, pageOptions, plans, slugify } from '../../lib/siteDefaults';

const checkout = {
  starter: process.env.NEXT_PUBLIC_STARTER_SUBSCRIPTION_CHECKOUT_URL,
  business: process.env.NEXT_PUBLIC_BUSINESS_SUBSCRIPTION_CHECKOUT_URL,
  premium: process.env.NEXT_PUBLIC_PREMIUM_SUBSCRIPTION_CHECKOUT_URL,
  extra: process.env.NEXT_PUBLIC_EXTRA_PAGE_SUBSCRIPTION_CHECKOUT_URL
};

export default function Builder(){
 const [step,setStep]=useState(0); const [site,setSite]=useState(()=>createDefaultSite()); const [message,setMessage]=useState('');
 const tmpl=useMemo(()=>getTemplate(site.typeKey,site.styleKey),[site.typeKey,site.styleKey]);
 function update(p){setSite(s=>({...s,...p}))}
 function chooseType(key){const type=templateLibrary.find(t=>t.key===key); const ns=createDefaultSite({typeKey:key,styleKey:type.styles[0].key}); update({...ns,businessName:site.businessName,customerEmail:site.customerEmail,phone:site.phone,plan:site.plan,primaryColor:site.primaryColor,accentColor:site.accentColor})}
 function addPage(p){ if(site.pages.includes(p)) return; const limit=plans[site.plan]?.maxPages||1; if(site.pages.length>=limit && site.plan!=='premium'){ setMessage(`This plan includes ${limit} page(s). Extra pages are $10/month each.`); if(checkout.extra) window.open(checkout.extra,'_blank'); return;} update({pages:[...site.pages,p]});}
 function removePage(p){ if(p==='Home') return; update({pages:site.pages.filter(x=>x!==p)});}
 async function publishFree(){ const s={...site,slug:slugify(site.businessName)}; localStorage.setItem('cookieDraftSite',JSON.stringify(s)); const res=await fetch('/api/site/publish',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({site:s})}); const data=await res.json(); if(data.ok) location.href=`/checkout/success?paid=free`; else setMessage(data.error); }
 function checkoutPlan(){ const s={...site,slug:slugify(site.businessName)}; localStorage.setItem('cookieDraftSite',JSON.stringify(s)); const url=checkout[site.plan]; if(!url){setMessage('Checkout link missing in Vercel Environment Variables.');return;} location.href=url; }
 return <main className="builderShell"><aside className="builderSide"><h1>Cookie Mini Website Builder Pro</h1>{['Choose Type & Look','Website Info','Design','Pages & Wording','Preview & Publish'].map((x,i)=><button className={`stepBtn ${step===i?'active':''}`} onClick={()=>setStep(i)} key={x}>{i+1}. {x}</button>)}<div className="notice">Any issues, click the Contact Us button for help.</div><a className="btn light" href="/video-studio">AI Video Studio</a></aside><section className="builderMain"><div className="row"><div className="dashboard">{step===0&&<><h2>Choose the type and look</h2><div className="templateList">{templateLibrary.map(t=><button className={`pick ${site.typeKey===t.key?'active':''}`} onClick={()=>chooseType(t.key)} key={t.key}><strong>{t.type}</strong><br/><small>{t.styles.map(s=>s.name).join(' / ')}</small></button>)}</div><h3>Choose visual style</h3><div className="templateList">{tmpl.type.styles.map(s=><button className={`pick ${site.styleKey===s.key?'active':''}`} onClick={()=>update({styleKey:s.key})} key={s.key}><span style={{fontSize:34}}>{s.art}</span><br/><strong>{s.name}</strong><br/><small>{s.mood}</small></button>)}</div></>}
{step===1&&<><h2>Website Info</h2>{['businessName','customerEmail','phone','headline'].map(k=><div className="field" key={k}><label>{k==='businessName'?'Business / website name':k==='customerEmail'?'Customer email':'phone'===k?'Phone (optional)':'Homepage headline'}</label><input value={site[k]||''} onChange={e=>update({[k]:e.target.value})}/></div>)}<div className="field"><label>Homepage description</label><textarea value={site.description} onChange={e=>update({description:e.target.value})}/></div><div className="field"><label>Offer section title</label><input value={site.offerTitle} onChange={e=>update({offerTitle:e.target.value})}/></div>{site.offers.map((o,i)=><div className="card" key={i}><h3>Offer Box {i+1}</h3><input value={o.title} onChange={e=>{const offers=[...site.offers];offers[i]={...offers[i],title:e.target.value};update({offers})}}/><textarea value={o.text} onChange={e=>{const offers=[...site.offers];offers[i]={...offers[i],text:e.target.value};update({offers})}}/></div>)}</>}
{step===2&&<><h2>Design</h2><div className="field"><label>Plan</label><select value={site.plan} onChange={e=>update({plan:e.target.value})}>{Object.entries(plans).map(([k,v])=><option value={k} key={k}>{v.label} - {v.price}</option>)}</select></div><div className="row"><div className="field"><label>Main color</label><input type="color" value={site.primaryColor} onChange={e=>update({primaryColor:e.target.value})}/></div><div className="field"><label>Accent color</label><input type="color" value={site.accentColor} onChange={e=>update({accentColor:e.target.value})}/></div></div><p>Change type/look anytime from Step 1. The preview updates right away.</p></>}
{step===3&&<><h2>Pages & Wording</h2><p>{plans[site.plan]?.label} includes {plans[site.plan]?.maxPages>=99?'all built-in pages':`${plans[site.plan]?.maxPages} page(s)`}.</p><div className="templateList">{pageOptions.map(p=><button className={`pick ${site.pages.includes(p)?'active':''}`} key={p} onClick={()=>site.pages.includes(p)?removePage(p):addPage(p)}>{site.pages.includes(p)?'✓ ':''}{p}</button>)}</div>{site.pages.filter(p=>p!=='Home').map(p=><div className="field" key={p}><label>{p} wording</label><textarea value={site.sections?.[p]||''} onChange={e=>update({sections:{...site.sections,[p]:e.target.value}})}/></div>)}<h3>Gallery / media links</h3><MediaEditor site={site} update={update}/></>}
{step===4&&<><h2>Preview & Publish</h2>{message&&<div className="notice error">{message}</div>}<p>Your website name will be:</p><div className="notice"><strong>{slugify(site.businessName)}.cookiesdigitalcreations.com</strong></div>{site.plan==='free'?<button className="btn" onClick={publishFree}>Publish Free Page</button>:<button className="btn" onClick={checkoutPlan}>Go to {plans[site.plan]?.price} Checkout</button>}</>}
</div><div className="previewSticky"><SitePreview site={site}/></div></div></section></main> }
function MediaEditor({site,update}){function add(){update({media:[...(site.media||[]),{kind:'link',url:'',title:''}]})}function set(i,m){const media=[...(site.media||[])];media[i]=m;update({media})}function remove(i){update({media:site.media.filter((_,x)=>x!==i)})}function file(i,file){const r=new FileReader();r.onload=()=>set(i,{kind:'image',url:r.result,title:file.name});r.readAsDataURL(file)}return <div>{(site.media||[]).map((m,i)=><div className="card" key={i}><div className="row"><input placeholder="Title" value={m.title||''} onChange={e=>set(i,{...m,title:e.target.value})}/><select value={m.kind} onChange={e=>set(i,{...m,kind:e.target.value})}><option value="link">Video/social/media link</option><option value="image">Image upload</option></select></div>{m.kind==='image'?<input type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&file(i,e.target.files[0])}/>:<input placeholder="https://youtube.com/..." value={m.url||''} onChange={e=>set(i,{...m,url:e.target.value})}/>}<button className="btn dark" onClick={()=>remove(i)}>Remove</button></div>)}<button className="btn dark" onClick={add}>Add Media</button></div>}
